[variables]
NIXPACKS_NODE_VERSION = '20'

[phases.setup]
nixPkgs = ['...']

[phases.build]
cmds = [
  'mkdir config',
  'echo ${{ retouch.CONFIG }} | base64 --decode > config/config.json',
  'npm install',
  'npm run build'
]

[start]
cmd = 'npm start'