name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir config
          echo ${{ secrets.CONFIG }} | base64 --decode > config/config.json
          echo ${{ secrets.DEBUG }} | base64 --decode > config/debug.json
          echo ${{ secrets.BOT_SITES }} | base64 --decode > config/bot-sites.json
          echo ${{ secrets.REDIS_URL }} > .env
          echo $NODE_ENV >> .env
      - run: docker compose up -d
      - name: Test
        run: docker compose exec server npm test
