name: tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: |
          mkdir config
          echo "${{ secrets.CONFIG }}" > config/config.json
      - run: |
          npm install
          npm test

