name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir config
          echo ${{ secrets.CONFIG }} | base64 --decode > config/config.json
          echo ${{ secrets.DEBUG }} | base64 --decode > config/debug.json
          echo ${{ secrets.BOT_SITES }} | base64 --decode > config/bot-sites.json
          echo REDIS_URL=${{ secrets.REDIS_URL }} > .env
      - name: Test
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from server
